/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cakes.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cakes-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.24, 0.47, 0]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/cakes-transformed.glb')
