/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 popsicle.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/popsicle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/popsicle.glb')
